apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-amazing-docs
  title: My amazing docs
  description: OMG These docs are crazy good
  annotations:
    github.com/project-slug: bcgov/devhub-user-test-participant-4
    backstage.io/techdocs-ref: dir:.
    developer.gov.bc.ca/source_template: default/docs-template-v2
spec:
  type: documentation
  lifecycle: experimental
  owner: developer-experience
