site_name: "My amazing docs"
site_description: "OMG These docs are crazy good"
docs_dir: "docs"
repo_url: "bcgov/devhub-user-test-participant-4"
edit_uri: "edit/main/docs"
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
